### ISSUE TITLE
How to use with npm and webpack?

### ISSUE THREAD

**Issue by johnmee** [hootsuite/grid#102]
Similar to issue #98 I'm trying to work out how to use this with [webpack](https://webpack.github.io) directly from the [npm package](https://www.npmjs.com/package/grid-list) without much success.

**require('grid-list')** loads the _gridList.js_ ok, but _jquery.gridList.js_ is not loaded.

Following it up with **require('grid-list/src/jquery.gridList.js')** generates this error...

> ERROR in ./\~/grid-list/src/jquery.gridList.js
Module not found: Error: Cannot resolve module 'gridlist' in /home/john/project/node_modules/grid-list/src
 @ ./\~/grid-list/src/jquery.gridList.js 6:4-43

I've tried any number of incantations involving 'expose' and 'imports' without success.  I confess I don't know the internals of what happens to do much more than take potshots in the dark.

I do get success if I _resolve.alias_ the two files in the _webpack.config.js_.  With those in place I can just **require** both aliases and everything is good to go.

>     resolve: {
>        alias: {
>            'gridlist': path.join(SRC_PATH, 'libs', 'gridList.js'),
>            'jgridlist': path.join(SRC_PATH, 'libs', 'jquery.gridList.js')
>        }
>     }

Just wondering if anyone has struck upon an incantation that will work without the aliases?

**Comment by andrei-picus-hs** [comment]
Myes, it seems like the jQuery plugin wasn't [ever made](https://github.com/hootsuite/grid/blob/ee255749482aab8d47d5a2a33a65323d4d8c963c/src/jquery.gridList.js#L1-L2) for CommonJS. We could add `module.exports` and `require` calls, but we need to be careful with webpack because it understands both AMD and CommonJS and it will choose the first branch in that UMD boilerplate.

We could also make everything CommonJS and use webpack to publish a UMD package to npm/bower.

Leaving this open for ideas and/or PRs.

**Comment by RadValentin** [comment]
Just wanted to add that the defined module `gridlist` is incorrect, if it was set to `grid-list`, the name of the NPM package then it should get resolved ok for AMD

**Comment by RadValentin** [comment]
@johnmee Can you give it a shot (see my previous comment) and submit a PR if it works for you?

**Comment by johnmee** [comment]
A variation to solve this for webpack, without setting up aliases.

    window.GridList = require('grid-list/src/gridList.js');
    require('imports?define=>false!grid-list/src/jquery.gridList.js');

**Comment by olee** [comment]
Why wasn't this fixed?
Just changing the import from `gridlist` to `grid-list` should fix this problem....

**Comment by valentin-radulescu-hs** [comment]
@olee You're correct, feel free to open a PR and ping me for code review.

**Comment by valentin-radulescu-hs** [comment]
@olee fixed in #111
