### ISSUE TITLE
Unable to move cells to certain positions

### ISSUE THREAD

**Issue by Deco** [hootsuite/grid#21]
In Chrome 33.0.1750.152, cell dragging does not work as expected in certain situations.
In the following situation, attempting to drag a cell (e.g: 1) to be between one of the following pairs does not work: 3-2, 2-7, 7-6, 6-9, 9-4, 3-5 and 5-10.

![screen shot 2014-04-01 at 8 45 07 am](https://cloud.githubusercontent.com/assets/95221/2574620/1fe5a6ba-b937-11e3-9211-ef09a70078a7.png)

**Comment by solerman** [comment]
I think this one is fixed already
