### ISSUE TITLE
We need 3 features

### ISSUE THREAD

**Issue by FreezeSoul** [hootsuite/grid#38]
I compared your grid with gridster, your grid is very smart, also has a Good performance.
But It has 3 important features Unrealized
1. Dynamic creation（in codebehind）
2. Drag resize 
3. Implement resizing of item height
Look forward to your improved version，Thank you for your good ideas。

**Comment by RonakKhandelwal** [comment]
@skidding if I could get an update on this, it would be great since no. 1 is a very important feature that we need and it is the sole issue standing between our project and this amazing lib. So if I could get an update I would be so grateful.

**Comment by git-ashish** [comment]
@RonakKhandelwal You could consider bridging the gap by making a contribution, its an open source project.

**Comment by RonakKhandelwal** [comment]
@git-ashish I definitely would have if I wasn't swamped with this ongoing project. I wanted a library which would take care of all these features so that I have space for some extra work on my plate, anyways I saw a guy who was interested in submitting a pr for the same issue but he never got a response.

**Comment by valentin-radulescu-hs** [comment]
@RonakKhandelwal I'm open to doing a code review if he submits a PR, don't know to whom you're referring to...

**Comment by RonakKhandelwal** [comment]
#82 is the one I'm talking about.

**Comment by RonakKhandelwal** [comment]
A solution for no 2. Put this code just under the place where you are actually creating the grid. Somewhere around "  $('#grid').gridList({ " function




```
$( "#grid li" ).resizable({
    ghost: true,
    grid: [$('#grid').data("_gridList")._cellWidth, $('#grid').data("_gridList")._cellHeight],
    minHeight: 10,
    minWidth: 10,
    start: function (event, ui) {
      $("#grid").data("resizing", true);
    },
    stop: function (event, ui) {
        var minHeight = $('#grid').data("_gridList")._cellHeight;
        var minWidth = $('#grid').data("_gridList")._cellWidth;
        $("#grid").data("resizing", false);
        var li = $(ui.originalElement)[0];
        if(!event.revert) {
            var opt = {
            w: Math.round(ui.size.width/ $('#grid').data("_gridList")._cellWidth),
            h: Math.round(ui.size.height / $('#grid').data("_gridList")._cellHeight)
        };
        $('.grid').gridList('resizeItem', li, opt);
        }
    }
  });
```

**Comment by dusiromulo** [comment]
Hey guys, I'm doing a widget for Django that uses this libs. I've implemented add and remove elements, if you want I can post it here.

**Comment by RonakKhandelwal** [comment]
@dusiromulo please do, even I am on my way of implementing that and I hope that the author can incorporate the changes in the lib

**Comment by dusiromulo** [comment]
What is the best way to put my code here in this page? I've implemented some functions inside gridList.js and jquery.gridList.js and code of theses files are too big.

**Comment by dusiromulo** [comment]
Here is the zip link: https://drive.google.com/file/d/0B0wKFMQ1VZeCZ0o2VU5vajVkWlk/view?usp=sharing

**Comment by dusiromulo** [comment]
Some important changes:

1) Sorry, but I have to change the DemoGrid structure, because I want two grids in the same page.
2) Inside jquery.gridList.js on function _applyPositionToItems i'm applying the respective position in the respective HTML element. I need this for calculate the new element position.
3) Inside gridList.js I create removeItem function, for remove the item of structure and apply new position for items below this item.

Sorry for bad english too.

**Comment by RonakKhandelwal** [comment]
@valentin-radulescu-hs good enough for pr? If you want some different implementation let me know I'll submit a pr myself.

**Comment by RonakKhandelwal** [comment]
@dusiromulo I tested your solution, the remove overlaps items when the items are of different sizes.

**Comment by valentin-radulescu-hs** [comment]
@dusiromulo Would you mind opening a PR? It would make it much easier to review. If you're unfamiliar with the git workflow there are plenty of tutorials online, some I used are: [this](https://try.github.io/) and [this](https://www.codeschool.com/courses/try-git).

The process would be:

1. Fork this repo and clone it on your machine
2. Make a branch and apply your changes
3. Publish the branch and make a PR to this repo for that branch

**Comment by dusiromulo** [comment]
Yeah, I'll do this!

**Comment by KarthikJayakumar** [comment]
+1 Any Updates?
