### ISSUE TITLE
Grid does not display in IE8

### ISSUE THREAD

**Issue by rjub** [hootsuite/grid#43]
Why does the grid demo not work in IE8?

**Comment by valentin-radulescu-hs** [comment]
IE8 compatibility has never been a priority for us, IE9+ should work fine though. 

You could probably get the get the grid working for older browsers if you include a bunch of polyfills for stuff like [Array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Polyfill), [Array.indexOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf#Polyfill) etc.
