### ISSUE TITLE
more events?

### ISSUE THREAD

**Issue by patrioticcow** [hootsuite/grid#48]
hello,

how can one drag a block and switch it with another block only once?
what about events like, onSort?

thanks

**Comment by andrei-picus-hs** [comment]
> what about events like, onSort?

See #61.

> how can one drag a block and switch it with another block only once?

This doesn't seem related to events. What do you mean by this?

**Comment by patrioticcow** [comment]
At the time I placed this question, it made sense to ask it, now it doesn't :) sorry
