### ISSUE TITLE
Add support for saving and loading layout

### ISSUE THREAD

**Issue by drma-dev** [hootsuite/grid#57]
As the API page is unavailable, I do not know if already exists. But what happens after the user customizes the page layout? Is there any way to save this layout and retrieve later?

**Comment by andrei-picus-hs** [comment]
> As the API page is unavailable

What API page? We have the API docs in the [README](https://github.com/uberVU/grid/blob/20531d60a6900c421d310a8e43213224183ac03e/README.md#api).

> Is there any way to save this layout and retrieve later?

If you're using the GridList API directly, you can get the grid by inspecting the [items property](https://github.com/uberVU/grid/blob/20531d60a6900c421d310a8e43213224183ac03e/src/gridList.js#L48) on the instance or by looking at the [grid property](https://github.com/uberVU/grid/blob/20531d60a6900c421d310a8e43213224183ac03e/src/gridList.js#L96-L120). If you're using the jQuery plugin, you can get the GridList instance by doing [$("#myGrid").data('_gridList').gridList](https://github.com/uberVU/grid/blob/20531d60a6900c421d310a8e43213224183ac03e/src/jquery.gridList.js#L336). From there on you can use your favorite way of doing persistent storage e.g. local storage or cookies.

**Comment by RonakKhandelwal** [comment]
@dhiogoacioli  although I have implemented this feature myself but would you mind showing me your implementation for loading the layout? I think I am missing out on some cases.

**Comment by imMatt** [comment]
@RonakKhandelwal Any chance you'd be able to share how you implemented saving and loading?

**Comment by RonakKhandelwal** [comment]
@imMatt I wouldn't be able to share the code for it but I'll just tell you the gist of it. I stored each "widget" or element inside a json object with its x,y,w,h parameters and while loading it I read from that. If you have a look at the available api it should be fairly straightforward.
