### ISSUE TITLE
bower version outdated

### ISSUE THREAD

**Issue by avilaj** [hootsuite/grid#60]
Hello guys, i'm having troubles getting it working with bower, everything works, but there is a problem when i call resizeItem(element, {w:2, h:2}). It is working with the previous version. I don't know what i have to do to use in bower the version 2 of the library.

**Comment by gitsilvan** [comment]
I also had a problem with the bower version. It worked when I added the "master" branch name at the end of the install command. So instead of doing `bower install hootsuite/grid` you can try `bower install hootsuite/grid#master`. Worked for me! Installed the actual newest version.

**Comment by valentin-radulescu-hs** [comment]
Should work fine now if you install the latest version (0.4.0 ATM) .
```
bower install grid-list#0.4.0
```

Unfortunately due to a tag issue on our end bower will try to pull in `v1.0.0` which is actually outdated as it's been pointed out.
