### ISSUE TITLE
Insert data into grid items like Normal HTML or Highcharts plugin.

### ISSUE THREAD

**Issue by matpulis** [hootsuite/grid#63]
This is an awsome repository, but I cant quite figure out how can I input data into each individual grid item like normal HTML. I am building a widget dashboard and would like to include plugins from highcharts. And is it possible to save a layout after you've edited it ? 

Thanks you

**Comment by andrei-picus-hs** [comment]
> how can I input data into each individual grid item like normal HTML

Check out the [jQuery plugin](https://github.com/uberVU/grid/blob/20531d60a6900c421d310a8e43213224183ac03e/src/jquery.gridList.js).

> is it possible to save a layout after you've edited it ?

See https://github.com/uberVU/grid/issues/57.
