### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by passkey1510** [hootsuite/grid#74]
The default direction of the grid is 'horizontal' as set in https://github.com/hootsuite/grid/blob/master/src%2FgridList.js#L85 meanwhile the doc states that the default direction is 'vertical', which could cause a couple of minutes looking at the source code to find out :)

Otherwise, thanks for the great lib!

**Comment by andrei-picus-hs** [comment]
Fixed in #75. @passkey1510 thanks for spotting this.
