### ISSUE TITLE
JavaScript mode Not working

### ISSUE THREAD

**Issue by Horray** [hootsuite/grid#89]
I"m trying to create a the grid framework using a JSFiddle. The problem is, nothing happens when I do it. Here's the JSFiddle:

https://jsfiddle.net/xrwbybb8/

**Comment by andrei-picus-hs** [comment]
The `GridList` lib doesn't work with DOM. The jQuery plugin on the other hand... Check out the [source](https://github.com/hootsuite/grid/blob/0e995bb406da7e4c9ae71623c96a33608915f942/demo/load.js) for the demo page for details on usage.
