### ISSUE TITLE
npm - packages

### ISSUE THREAD

**Issue by BoyZeePoole** [hootsuite/grid#98]
There is already a package on npm for grid-list, but none for jquery.gridList?
We are using systemJS with angular and import our components via package.json making it difficult to use the jquery.gridList.

**Comment by NiGhTTraX** [comment]
You should be able to import the jQuery plugin by its path in the repo i.e.
`require('gridlist/src/jquery.gridList.js')`.

**Comment by BoyZeePoole** [comment]
Awesome, I'm not using require, but import 'gridlist/src/jquery.gridList.js', worked just fine...
Thanks
